### ISSUE TITLE
Information on the behavior of fritzinfluxdb-dashboard with Grafana 9.2

### ISSUE THREAD

**Issue by dp20eic** [bb-Ricardo/fritzinfluxdb#61] opened 2022-10-13 11:15 UTC
Hi,
I love this project and I love to play around, so I install fritzinfluxdb from next-release branch. And the Dashboard is imported to Grafana 9.1.6 all is fine, as you see:
<details picture>

![grafik](https://user-images.githubusercontent.com/71387331/195578898-6cb40da9-afaa-4d06-b1b8-d3eb1ebe9ac8.png)

</details picture>

But if I upgrade to Grafana 9.2 the same Dashboard ist corrupted, see next picture:
<details picture>

![grafik](https://user-images.githubusercontent.com/71387331/195580102-587ff030-1e81-4c01-bde6-673a1aeddb30.png)

</details picture>

And with Grafana 9.2 it looks like the query is not finished:
<details query circle>

![grafik](https://user-images.githubusercontent.com/71387331/195581174-e0cd7891-f846-41b3-a8ba-0157d6ed3ae8.png)

</details query circle>

I try to find more information or run Grafana with debug, but this can take some time.

kind regards
Bernd

**Comment by bb-Ricardo** [comment] 2022-10-13 12:03
Hi,

Thank you for this information. I have to investigate this in my setup. Not sure why it is not working. This log annotation loading icon is there even in Grafana 9.1 and previous.

**Comment by ronaldn1969** [comment] 2022-10-13 13:09
Hi 

this is quite interesting. I updated my TIG stack to Grafana 9.2.0 and checked with my installation. I'm still running the "rewrite-adding-async" branch. With my own dashboard (no Log annotations) I have no problems with 9.2.0. If I run the github dashboard I face the same problem like Bernd. If I use the old TIG with Grafana 9.1.5 there is also no problem. 

I deleted the log annotation in the dashboard settings and then it run without problems under 9.2.0.

**Comment by bjtox** [comment] 2022-10-16 23:00
i can confirm with, with grafana 9.2 for sistem dashboard if i remove "annotation" property it work correctly

**Comment by dp20eic** [comment] 2022-10-17 14:10
Ok, forgott to write :(

as I did my checks, I saw in my two instances of grafan V9.1.6 and grafana 9.2 the following differences.

Grafana-9-1-6
<details> 

![grafik](https://user-images.githubusercontent.com/71387331/196197461-77d19157-0ed9-4b37-8e46-ed9b465c655b.png)
</details>

Grafana 9.2
<details>

![grafik](https://user-images.githubusercontent.com/71387331/196198265-19eb73ad-3174-4764-be67-1971e55be211.png)
</details>

After I switched off the annotation, save the dashboard and enable the annotation again it works but with out annotation, the query is empty.
After copy the query and save the dashboard again it works the same as under Grafana 9.1.6.

VG
Bernd

**Comment by bb-Ricardo** [comment] 2022-10-17 14:32
Hi @dp20eic,

So more or less it seems a migration error in Grafana while upgrading to 9.2. Will check tonight if there is already an open ticket.

Thank you for the finding.

**Comment by dp20eic** [comment] 2022-10-17 14:39
Hi @bb-Ricardo,
> So more or less it seems a migration error in Grafana while upgrading to 9.2. Will check tonight if there is already an open ticket.

Yes, I did the upgrade on my productive Grafane some minutes ago and after copy the query and save the dashboard, it runs without problems.

Your welcome

**Comment by bb-Ricardo** [comment] 2022-10-17 15:12
I couldn't find an existing issue. Do you mind if I use your screenshots in a new Grafana issue?

**Comment by dp20eic** [comment] 2022-10-17 17:56
Hi @bb-Ricardo,
> I couldn't find an existing issue. Do you mind if I use your screenshots in a new Grafana issue?

Yes no problem.

VG
Bernd

**Comment by bb-Ricardo** [comment] 2022-10-17 19:05
Created an issue here: https://github.com/grafana/grafana/issues/57122

**Comment by bb-Ricardo** [comment] 2022-10-29 09:08
Hi,

maybe you want to try the new all flux dashboards here:

https://github.com/bb-Ricardo/fritzinfluxdb/blob/next-release/README.md#grafana

I would just close this issue. I have no glue how long it will take to fix this in Grafana.

What do you think?

**Comment by bgoerner** [comment] 2022-10-29 14:19
> 

Unfortunately, the new dashboards on branch next-release do not work with influx1.8. :-(

the links in https://github.com/bb-Ricardo/fritzinfluxdb/blob/next-release/README.md#grafana are dead (404).

**Comment by bb-Ricardo** [comment] 2022-10-29 14:31
The links will work once it is merged to main.

True, the Flux dashboards won't work witch Influxdb 1.8 due to missing functionality and support in 1.8.

You should be able to delete and reimport the systems dashboard for influx 1.

**Comment by bgoerner** [comment] 2022-10-29 14:38
unfortunately my attempt fails. the error remains after new import.

**Comment by bb-Ricardo** [comment] 2022-10-29 20:45
Hey @bgoerner,

sorry for the inconvenience. I false assumed this was a migration bug. But it's more a general issue with 9.2 and INFLUX query migrations.

However, I think I found a solution which works with 9.1 and 9.2. I pushed another change to `next-release`. Would you mind checking out if the annotations work right away in your setup? 

commit ID: 7ca72827853f8a0e9bd9bf97cf72b002e4980a31

Thank you

**Comment by dp20eic** [comment] 2022-10-30 15:54
Hi,

next Thursday, I have some time to switch complete with "fritzinfluxdb" from influxdb 1.8 to influxdb2 2.4 also with migrate to the new dashboards using flux.

with kind regards
Bernd

**Comment by bgoerner** [comment] 2022-10-30 21:27
> 

hey, cool... it works now.

**Closed** 2022-10-31 23:41 UTC
Labels: awaiting-answer

**Comment by dp20eic** [comment] 2022-11-03 13:02
Hello Ricardo,

as I told, I did the migration today too.
New "fritzinfluxdb V1.1" -> influxdb2 V2.4 -> Grafana 9.2.4 (new Dashboards with Flux) as I see now for the last 10 - 15 minutes all ist running like a charm.

Good work and thank you for this great software.

VG
Bernd

**Comment by bb-Ricardo** [comment] 2022-11-03 15:07
Hi @dp20eic,

This sounds great and happy that it finally worked out.
