### ISSUE TITLE
Getting error FritzBox metric type

### ISSUE THREAD

**Issue by Leviathan09** [bb-Ricardo/fritzinfluxdb#57] opened 2022-09-24 12:34 UTC
Hi,
i installed this today and when i perform `./fritzinfluxdb.py` i get the follwing outpu

```
2022-09-24 14:26:21,584 - INFO: Starting fritzinfluxdb v1.0.1 (2022-08-22)
2022-09-24 14:26:21,585 - INFO: Done reading config files
2022-09-24 14:26:21,638 - INFO: Successfully parsed config
2022-09-24 14:26:21,651 - INFO: Connection to InfluxDB v2.4.0 established and bucket is present
2022-09-24 14:26:26,511 - INFO: Successfully established FritzBox TR-069 session
2022-09-24 14:26:29,064 - INFO: Successfully established FritzBox Lua session
2022-09-24 14:26:29,064 - INFO: Successfully connected to FritzBox '192.168.112.1' (fritz.box) Model: FRITZ!Box 7590 - FW: 7.39
2022-09-24 14:26:29,064 - INFO: Starting main loop
2022-09-24 14:26:30,047 - INFO: Requested invalid action 'GetInfo' for service: WANPPPConnection:1
2022-09-24 14:26:30,047 - INFO: Querying action 'GetInfo' will be disabled
2022-09-24 14:26:30,047 - INFO: All actions for service 'WANPPPConnection:1' are unavailable. Disabling service.
2022-09-24 14:26:39,112 - ERROR: FritzBox metric type '<class 'dict'>' does not match data: <class 'list'>
2022-09-24 14:26:39,112 - ERROR: FritzBox metric type '<class 'dict'>' does not match data: <class 'list'>
2022-09-24 14:26:39,112 - ERROR: FritzBox metric type '<class 'dict'>' does not match data: <class 'list'>
2022-09-24 14:26:39,112 - ERROR: FritzBox metric type '<class 'dict'>' does not match data: <class 'list'>
```
```
2022-09-24 14:26:42,165 - INFO: Unable to request FritzBox Lua service 'DSL Info'
2022-09-24 14:26:42,166 - INFO: FritzBox Lua service 'DSL Info' will be disabled.
2022-09-24 14:26:44,822 - INFO: Unable to request FritzBox Lua service 'Cable Info'
2022-09-24 14:26:44,822 - INFO: FritzBox Lua service 'Cable Info' will be disabled.
2022-09-24 14:26:50,574 - ERROR: FritzBox metric type '<class 'dict'>' does not match data: <class 'list'>
2022-09-24 14:26:50,574 - ERROR: FritzBox metric type '<class 'dict'>' does not match data: <class 'list'>
2022-09-24 14:26:50,575 - ERROR: FritzBox metric type '<class 'dict'>' does not match data: <class 'list'>
2022-09-24 14:26:50,575 - ERROR: FritzBox metric type '<class 'dict'>' does not match data: <class 'list'>
```

Maybe someone can explain what this means

**Comment by bb-Ricardo** [comment] 2022-09-24 15:31
This is fixt in branch `next-release`. Are you able to try this one please?

**Comment by Leviathan09** [comment] 2022-09-24 20:37
Cloned the next-release branch and edited the *.ini
Now i get way more output when running `./fritzinfluxdb.py`, but still there is the same error

```
2022-09-24 22:33:06,684 - INFO: Starting fritzinfluxdb v1.0.1 (2022-08-22)
2022-09-24 22:33:06,685 - INFO: Done reading config files
2022-09-24 22:33:06,756 - INFO: Successfully parsed config
2022-09-24 22:33:06,772 - INFO: Successfully create InfluxDB database mapping 'FritzBox'
2022-09-24 22:33:06,772 - INFO: Connection to InfluxDB v2.4.0 established and bucket is present
2022-09-24 22:33:11,543 - INFO: Successfully established FritzBox TR-069 session
2022-09-24 22:33:14,052 - INFO: Successfully established FritzBox Lua session
2022-09-24 22:33:14,052 - INFO: Successfully connected to FritzBox '192.168.112.1' (fritz.box) Model: FRITZ!Box 7590 - FW: 7.39
2022-09-24 22:33:14,053 - INFO: Starting main loop
2022-09-24 22:33:14,922 - INFO: Requested invalid action 'GetInfo' for service: WANPPPConnection:1
2022-09-24 22:33:14,923 - INFO: Querying action 'GetInfo' will be disabled
2022-09-24 22:33:14,923 - INFO: All actions for service 'WANPPPConnection:1' are unavailable. Disabling service.
2022-09-24 22:33:24,203 - ERROR: FritzBox metric type '<class 'dict'>' does not match data: <class 'list'>
2022-09-24 22:33:24,203 - ERROR: FritzBox metric type '<class 'dict'>' does not match data: <class 'list'>
2022-09-24 22:33:24,203 - ERROR: FritzBox metric type '<class 'dict'>' does not match data: <class 'list'>
2022-09-24 22:33:24,203 - ERROR: FritzBox metric type '<class 'dict'>' does not match data: <class 'list'>
```

**Comment by bb-Ricardo** [comment] 2022-09-25 14:18
Hi, can you run it with the `-v` command line option? Then I can see which query causes this issue. Thank you.

**Comment by Leviathan09** [comment] 2022-09-25 20:02
> Hi, can you run it with the `-v` command line option? Then I can see which query causes this issue. Thank you.
Done it, the output is huge so i put it into pastbin -> [long_log](https://pastebin.com/8hm9JYkq)

**Comment by bb-Ricardo** [comment] 2022-09-26 18:26
Hi @Leviathan09,

Thank you for the log, I got it. You should remove it as it contains more or less sensitive data.

I found the issue. It was fixed for 7.29 but not for 7.39. No it should work. Also found another issue where AVM seemed to have changed the data endpoints for DSL info.

Can you try the latest `next-release` and see if it's fixed for you?

Thank you

**Comment by Leviathan09** [comment] 2022-09-26 18:41
It works now without any issues
Thank you for your help

**Comment by bb-Ricardo** [comment] 2022-09-26 18:48
That's great. Then I will close this issue.

**Closed** 2022-09-26 18:48 UTC

**Comment by littlezaphod** [comment] 2022-11-18 18:42
Dear Ricardo,
I am also getting this error. I am using the next-release as you suggested. Fritzbox7490, FW 7.28, see output below.

INFO: Starting fritzinfluxdb v1.1.0-beta.2 (2022-11-XX)
INFO: Done reading config files
INFO: Successfully parsed config
INFO: Connection to InfluxDB 1.8.10 established and database present
INFO: Successfully established FritzBox TR-069 session
INFO: Successfully established FritzBox Lua session
INFO: Successfully connected to FritzBox '192.168.0.1' (fritz.box) Model: FRITZ!Box 7490 (DSL) - FW: 7.29
INFO: Starting main loop
ERROR: FritzBox metric type '<class 'list'>' does not match data: <class 'dict'>
ERROR: FritzBox metric type '<class 'list'>' does not match data: <class 'dict'>
ERROR: FritzBox metric type '<class 'list'>' does not match data: <class 'dict'>
ERROR: FritzBox metric type '<class 'list'>' does not match data: <class 'dict'>
ERROR: FritzBox metric type '<class 'list'>' does not match data: <class 'dict'>

**Comment by bb-Ricardo** [comment] 2022-11-18 20:54
Version 1.1.0 has been released already. You might need to do a `git pull again`.

Can you run it with the option `-v` so we can see where and what the issue is.

Thank you.
