### ISSUE TITLE
Failed to connect to FritzBox 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by FinnHuelsbusch** [bb-Ricardo/fritzinfluxdb#48] opened 2022-09-05 22:35 UTC
Hi, 
I'm currently setting up fritzinfluxdb through docker-compose. I managed to get a connection to the InfluxDB. I also managed to get a connection to the fritzbox (at least I do not get the error for wrong credentials anymore). But now I am stuck with the error seen below. 
I can not figure out on my own what the actual problem is because the error-message is very generic. 

Hope that someone can help me out or reproduce and fix the error. 

```
2022-09-05 22:19:23,773 - INFO: Starting fritzinfluxdb v1.0.1 (2022-08-22)
2022-09-05 22:19:23,775 - DEBUG: Config: influxdb.version = 2
2022-09-05 22:19:23,776 - DEBUG: Config: influxdb.hostname = influxdb
2022-09-05 22:19:23,776 - DEBUG: Config: influxdb.port = 8086
2022-09-05 22:19:23,777 - DEBUG: Config: influxdb.tls_enabled = False
2022-09-05 22:19:23,777 - DEBUG: Config: influxdb.verify_tls = False
2022-09-05 22:19:23,778 - DEBUG: Config: influxdb.measurement_name = fritzbox
2022-09-05 22:19:23,778 - DEBUG: Config: influxdb.username = None
2022-09-05 22:19:23,779 - DEBUG: Config: influxdb.password = None
2022-09-05 22:19:23,779 - DEBUG: Config: influxdb.database = None
2022-09-05 22:19:23,780 - DEBUG: Config: influxdb.token = removed for GitHub
2022-09-05 22:19:23,780 - DEBUG: Config: influxdb.organisation = myOrg
2022-09-05 22:19:23,781 - DEBUG: Config: influxdb.bucket = fritzinfluxdb
2022-09-05 22:19:23,803 - DEBUG: Config: fritzbox.hostname = 192.168.188.1
2022-09-05 22:19:23,804 - DEBUG: Config: fritzbox.username = fritzinflux
2022-09-05 22:19:23,804 - DEBUG: Config: fritzbox.password = removed for GitHub
2022-09-05 22:19:23,805 - DEBUG: Config: fritzbox.port = 49000
2022-09-05 22:19:23,805 - DEBUG: Config: fritzbox.tls_enabled = False
2022-09-05 22:19:23,806 - DEBUG: Config: fritzbox.verify_tls = False
2022-09-05 22:19:23,806 - DEBUG: Config: fritzbox.connect_timeout = 10
2022-09-05 22:19:23,807 - DEBUG: Config: fritzbox.request_interval = 10
2022-09-05 22:19:23,807 - DEBUG: Config: fritzbox.box_tag = fritz.box
2022-09-05 22:19:23,808 - DEBUG: Config: fritzbox.timezone = Europe/Berlin
2022-09-05 22:19:23,960 - INFO: Successfully parsed config
2022-09-05 22:19:23,996 - DEBUG: InfluxDB bucket 'fritzinfluxdb' exists
2022-09-05 22:19:23,996 - DEBUG: InfluxDB bucket 'fritzinfluxdb' present, checking database name mapping
2022-09-05 22:19:24,005 - DEBUG: InfluxDB bucket 'fritzinfluxdb' has a database mapping: fritzinfluxdb
2022-09-05 22:19:24,005 - INFO: Connection to InfluxDB v2.4.0 established and bucket is present
2022-09-05 22:19:24,006 - DEBUG: Initiating new FritzBox TR-069 session
2022-09-05 22:19:26,627 - ERROR: Failed to connect to FritzBox TR-069 '192.168.188.1': 'NoneType' object has no attribute 'strip'
2022-09-05 22:19:26,627 - INFO: Disabling queries via Lua. Fritz!OS version must be at least 7.XX
2022-09-05 22:19:26,628 - ERROR: Initializing connection to FritzBox TR-069 failed
```

**Comment by bb-Ricardo** [comment] 2022-09-06 15:22
Hi,

Yes this seems to be a programming error to not offer a better error message.

Which Fritz!OS version are you using and which FritzBox model?

**Comment by FinnHuelsbusch** [comment] 2022-09-06 20:20
I'm currently running a FritzBox 7590 with Fritz!Os 07.29. 
I actually was able to fix the problem. A quick reboot of the FritzBox was the solution. 
And I want to thank you for providing this very nice dashboard + scraper. I really appreciate it. 

I also was able to reproduce the error by following these steps: 
1. Provide the wrong credentials to the docker Image.
2. Start the container 
3. Let it sit for a couple of minutes (tested with ~ 5 min) 
5. Rebuild the container, this time with the correct credentials. 
6. Log at the logs. The error is back. 

I hope this helps to narrow the error down.

**Comment by bb-Ricardo** [comment] 2022-09-06 20:40
Thank you for testing.

I have an ide that it has to do with the wrong credentials and back off. Every time you try the wrong credentials it will block the account a bit longer.

Will try to add a detection for wrong credentials on the TR69 handler.

**Comment by FinnHuelsbusch** [comment] 2022-09-07 09:42
Well that seems like a normal behaviour. But keep in mind that I got a more specific message prompting me, that my credentials are wrong, when they were. Only when I changed the credentials to the correct credentials the unspecific error started to appear.

**Comment by bb-Ricardo** [comment] 2022-09-07 12:46
good point, thank you for clarifying this. Will help to find a solution

**Comment by bb-Ricardo** [comment] 2022-09-12 20:44
Hi,

I tried to reproduce the error a few times but no luck. I got the message about the wrong credentials and a soon as I entered the correct ones the connection was successful without the above error.

Is it OK if we close this issue for now as I can't reproduce it?

**Comment by FinnHuelsbusch** [comment] 2022-09-15 13:44
Yes, that is completely fine. I was able to fix it with a simple restart and now I can't reproduce it. So closure seems to be the way to go.

**Closed** 2022-09-15 16:32 UTC
